# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tva9dryuk1naR7jESd32GYZjDAx_LJex
"""

#1
import matplotlib.pyplot as plt
import numpy as np

x=np.array([0,6])
y=np.array([0,250])

plt.plot(x,y)
plt.show()

#7
import matplotlib.pyplot as plt
import numpy as np

x=np.array([0,2,5,7,10])
y=np.array([2,7,9,23,2])

plt.plot(x,y)
plt.show()

#9
import matplotlib.pyplot as plt
import numpy as np

x=np.array([0,2,5,7,10])
y=np.array([2,7,9,23,2])

plt.plot(x,y, marker='D')
plt.show()

#13
import matplotlib.pyplot as plt
import numpy as np

x=np.array([0,2,5,7,10])
y=np.array([2,7,9,23,2])

plt.plot(x,y, marker='v',ms=20)
plt.show()

#14
import matplotlib.pyplot as plt
import numpy as np

x=np.array([0,2,5,7,10])
y=np.array([2,7,9,23,2])

plt.plot(x,y, 'v:r',ms=20,)
plt.show()

#15
import matplotlib.pyplot as plt
import numpy as np

x1=np.array([0,2,5,7,10])
y1=np.array([2,7,9,23,2])
x2=np.array([3,5,8,10,15])
y2=np.array([2,7,5,20,23])

plt.plot(x1,y1,x2,y2)
plt.show()

#16
import matplotlib.pyplot as plt
import numpy as np

x=np.array([0,2,5,7,10])
y=np.array([2,7,9,23,2])

plt.plot(x,y, marker='v',ms=20,mfc='r')
plt.show()

#27
import matplotlib.pyplot as plt
import numpy as np

x=np.array([0,2,5,7,10])
y=np.array([2,7,9,23,2])

plt.scatter(x,y)
plt.show()

#29
import matplotlib.pyplot as plt
import numpy as np

x=np.array([0,2,5,7,10])
y=np.array([2,7,9,23,2])
mycolor=['r','g','y','b','k']
plt.scatter(x,y,color=mycolor)
plt.show()

#30
import matplotlib.pyplot as plt
import numpy as np

x=np.array([0,2,5,7,10])
y=np.array([2,7,9,23,2])
mycolor=['r','g','y','b','k']
size=[10,50,60,100,200,]
plt.scatter(x,y,color=mycolor,s=size)
plt.show()

#33
import matplotlib.pyplot as plt
import numpy as np

x=np.array(['614-23','613-23','510-23'])
y=np.array([23,20,18])
plt.bar(x,y)
plt.show()

#36
import matplotlib.pyplot as plt
import numpy as np

x=np.array([25,25,25,25])
plt.pie(x)
plt.show()

#37
import matplotlib.pyplot as plt
import numpy as np

x=np.array([25,25,25,25])
mylabels=["Apples",'Bananas','Cherries','Apelsin']
plt.pie(x,labels=mylabels)
plt.show()

#39
import matplotlib.pyplot as plt
import numpy as np

x=np.array([25,25,25,25])
mylabels=["Apples",'Bananas','Cherries','Apelsin']
myexplode=[0.2,0.2,0.2,0.2]

plt.pie(x,labels=mylabels,explode=myexplode)
plt.show()

#41
import matplotlib.pyplot as plt
import numpy as np

x=np.array([25,25,25,25])
mylabels=["Apples",'Bananas','Cherries','Apelsin']
mycolor=['r','b','k','y']
myexplode=[0.2,0.2,0.2,0.2]

plt.pie(x,labels=mylabels,explode=myexplode,colors=mycolor)
plt.show()

#43
import matplotlib.pyplot as plt
import numpy as np

x=np.array([25,25,25,25])
mylabels=["Apples",'Bananas','Cherries','Apelsin']
myexplode=[0.2,0.2,0.2,0.2]

plt.pie(x,labels=mylabels,explode=myexplode)
plt.legend(title='four fruits')
plt.show()

#44

import matplotlib.pyplot as plt
import numpy as np
from matplotlib import cm
plt.style.use('_mpl-gallery')

x=np.arange(-5,5,0.25)
y=np.arange(-5,5,0.25)
x,y=np.meshgrid(x,y)
r=np.sqrt(x**2+y**2)
z=np.sin(r)

fig,ax=plt.subplots(subplot_kw={'projection':'3d'})
ax.plot_surface(x,y,z,vmin=z.min()*2,cmap=cm.Blues)

ax.set(xticklabels=[],
       yticklabels=[],
       zticklabels=[])
plt.show()